title: SG Courts Mobile App User Guide
remote_theme: opendocsg/opendoc-theme
timezone: Asia/Singapore
repository: opendocsg/opendoc-sg-courts-mobile-app-user-guide
plugins:
  - jekyll-include-cache
baseurl: ""
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics: null
fast_build: true
offline: false
preload_pages: true
styling_options:
  primary_brand_color: "#444"
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df
  logo_url: /
folders:
  - name: /
    title: SG Courts Mobile App User Guide
    order:
      - main.md
hide_toolbar:
  sidebar: false
  pdf: false
  github: false
